hibernate.connection.driver_class=org.mariadb.jdbc.Driver
hibernate.dialect=org.hibernate.dialect.MariaDBDialect
hibernate.connection.url=jdbc:mariadb://localhost:3306/retropvp
hibernate.connection.username=root
hibernate.connection.password=root
hibernate.default_catalog=retropvp