package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final



/**
 * Accesorio generated by hbm2java
 */
public class Accesorio  implements java.io.Serializable {


     private int idArticulo;
     private Consola consola;
     private Articulo articulo;

    public Accesorio() {
    }

    public Accesorio(Consola consola, Articulo articulo) {
       this.consola = consola;
       this.articulo = articulo;
    }
   
    public int getIdArticulo() {
        return this.idArticulo;
    }
    
    public void setIdArticulo(int idArticulo) {
        this.idArticulo = idArticulo;
    }
    public Consola getConsola() {
        return this.consola;
    }
    
    public void setConsola(Consola consola) {
        this.consola = consola;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }




}


