package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

/**
 * Accesorio generated by hbm2java
 */
@Setter
@Getter
public class Accesorio extends Articulo implements java.io.Serializable {


     private Integer idArticulo;
     private Consola consola;
     private Articulo articulo;

    public Accesorio() {
    }

    public Accesorio(Consola consola, Articulo articulo) {
       this.consola = consola;
       this.articulo = articulo;
    }

}


