package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

/**
 * Accesorio generated by hbm2java
 */
@Setter
@Getter
public class Accesorio extends Articulo implements java.io.Serializable {

     private Consola consola;

    public Accesorio() {
    }

    public Accesorio(Integer idArticulo, Consola consola) {
        this.setIdArticulo(idArticulo);
        this.consola = consola;
    }

}


