package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Articulo generated by hbm2java
 */
public class Articulo  implements java.io.Serializable {


     private Integer idArticulo;
     private String nombre;
     private BigDecimal precio;
     private String description;
     private Juego juego;
     private Set stocks = new HashSet(0);
     private Accesorio accesorio;
     private Consola consola;
     private Set articuloPedidos = new HashSet(0);

    public Articulo() {
    }

    public Articulo(String nombre, BigDecimal precio, String description, Juego juego, Set stocks, Accesorio accesorio, Consola consola, Set articuloPedidos) {
       this.nombre = nombre;
       this.precio = precio;
       this.description = description;
       this.juego = juego;
       this.stocks = stocks;
       this.accesorio = accesorio;
       this.consola = consola;
       this.articuloPedidos = articuloPedidos;
    }
   
    public Integer getIdArticulo() {
        return this.idArticulo;
    }
    
    public void setIdArticulo(Integer idArticulo) {
        this.idArticulo = idArticulo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Juego getJuego() {
        return this.juego;
    }
    
    public void setJuego(Juego juego) {
        this.juego = juego;
    }
    public Set getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set stocks) {
        this.stocks = stocks;
    }
    public Accesorio getAccesorio() {
        return this.accesorio;
    }
    
    public void setAccesorio(Accesorio accesorio) {
        this.accesorio = accesorio;
    }
    public Consola getConsola() {
        return this.consola;
    }
    
    public void setConsola(Consola consola) {
        this.consola = consola;
    }
    public Set getArticuloPedidos() {
        return this.articuloPedidos;
    }
    
    public void setArticuloPedidos(Set articuloPedidos) {
        this.articuloPedidos = articuloPedidos;
    }




}


