package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

/**
 * ArticuloPedido generated by hbm2java
 */
@Setter
@Getter
@AllArgsConstructor
public class ArticuloPedido  implements java.io.Serializable {


     private ArticuloPedidoId id;
     private Pedido pedido;
     private Articulo articulo;
     private int unidades;

    public ArticuloPedido() {
    }

    public ArticuloPedido(ArticuloPedidoId id, Pedido pedido, Articulo articulo, int unidades) {
       this.id = id;
       this.pedido = pedido;
       this.articulo = articulo;
       this.unidades = unidades;
    }

}


