package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Articulo generated by hbm2java
 */
@Setter
@Getter
public class Articulo  implements java.io.Serializable {


     private Integer idArticulo;
     private String nombre;
     private BigDecimal precio;
     private String description;
     private Juego juego;
     private Set stocks = new HashSet(0);
     private Accesorio accesorio;
     private Consola consola;
     private Set articuloPedidos = new HashSet(0);

    public Articulo() {
    }

    public Articulo(String nombre, BigDecimal precio, String description, Juego juego, Set stocks, Accesorio accesorio, Consola consola, Set articuloPedidos) {
       this.nombre = nombre;
       this.precio = precio;
       this.description = description;
       this.juego = juego;
       this.stocks = stocks;
       this.accesorio = accesorio;
       this.consola = consola;
       this.articuloPedidos = articuloPedidos;
    }

}


