package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final



/**
 * ArticuloPedido generated by hbm2java
 */
public class ArticuloPedido  implements java.io.Serializable {


     private ArticuloPedidoId id;
     private Pedido pedido;
     private Articulo articulo;
     private int unidades;

    public ArticuloPedido() {
    }

    public ArticuloPedido(ArticuloPedidoId id, Pedido pedido, Articulo articulo, int unidades) {
       this.id = id;
       this.pedido = pedido;
       this.articulo = articulo;
       this.unidades = unidades;
    }
   
    public ArticuloPedidoId getId() {
        return this.id;
    }
    
    public void setId(ArticuloPedidoId id) {
        this.id = id;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public int getUnidades() {
        return this.unidades;
    }
    
    public void setUnidades(int unidades) {
        this.unidades = unidades;
    }




}


