package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final



/**
 * ArticuloPedidoId generated by hbm2java
 */
public class ArticuloPedidoId  implements java.io.Serializable {


     private int idArticulo;
     private int idPedido;

    public ArticuloPedidoId() {
    }

    public ArticuloPedidoId(int idArticulo, int idPedido) {
       this.idArticulo = idArticulo;
       this.idPedido = idPedido;
    }
   
    public int getIdArticulo() {
        return this.idArticulo;
    }
    
    public void setIdArticulo(int idArticulo) {
        this.idArticulo = idArticulo;
    }
    public int getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(int idPedido) {
        this.idPedido = idPedido;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArticuloPedidoId) ) return false;
		 ArticuloPedidoId castOther = ( ArticuloPedidoId ) other; 
         
		 return (this.getIdArticulo()==castOther.getIdArticulo())
 && (this.getIdPedido()==castOther.getIdPedido());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdArticulo();
         result = 37 * result + this.getIdPedido();
         return result;
   }   


}


