package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Consola generated by hbm2java
 */
public class Consola  implements java.io.Serializable {


     private int idArticulo;
     private Articulo articulo;
     private Date anioLanzamiento;
     private Set accesorios = new HashSet(0);
     private Set juegos = new HashSet(0);

    public Consola() {
    }

    public Consola(Articulo articulo, Date anioLanzamiento, Set accesorios, Set juegos) {
       this.articulo = articulo;
       this.anioLanzamiento = anioLanzamiento;
       this.accesorios = accesorios;
       this.juegos = juegos;
    }
   
    public int getIdArticulo() {
        return this.idArticulo;
    }
    
    public void setIdArticulo(int idArticulo) {
        this.idArticulo = idArticulo;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public Date getAnioLanzamiento() {
        return this.anioLanzamiento;
    }
    
    public void setAnioLanzamiento(Date anioLanzamiento) {
        this.anioLanzamiento = anioLanzamiento;
    }
    public Set getAccesorios() {
        return this.accesorios;
    }
    
    public void setAccesorios(Set accesorios) {
        this.accesorios = accesorios;
    }
    public Set getJuegos() {
        return this.juegos;
    }
    
    public void setJuegos(Set juegos) {
        this.juegos = juegos;
    }




}


