package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Consola generated by hbm2java
 */
@Getter
@Setter
public class Consola extends Articulo implements java.io.Serializable {

     private int anioLanzamiento;
     private Set accesorios = new HashSet(0);
     private Set juegos = new HashSet(0);

    public Consola() {
    }

    public Consola(Integer idArticulo, int anioLanzamiento) {
        this.setIdArticulo(idArticulo);
        this.anioLanzamiento = anioLanzamiento;
    }

    public Consola(Integer idArticulo) {
        this.setIdArticulo(idArticulo);
    }

}


