package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Consola generated by hbm2java
 */
@Setter
@Getter
@AllArgsConstructor
public class Consola  implements java.io.Serializable {


     private int idArticulo;
     private Articulo articulo;
     private Date anioLanzamiento;
     private Set accesorios = new HashSet(0);
     private Set juegos = new HashSet(0);

    public Consola() {
    }

    public Consola(Articulo articulo, Date anioLanzamiento, Set accesorios, Set juegos) {
       this.articulo = articulo;
       this.anioLanzamiento = anioLanzamiento;
       this.accesorios = accesorios;
       this.juegos = juegos;
    }

}


