package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Enfrentamiento generated by hbm2java
 */
public class Enfrentamiento  implements java.io.Serializable {


     private Integer idEnfrentamiento;
     private String nombre;
     private String top;
     private int participantes;
     private Set rivals = new HashSet(0);

    public Enfrentamiento() {
    }

    public Enfrentamiento(String nombre, String top, int participantes, Set rivals) {
       this.nombre = nombre;
       this.top = top;
       this.participantes = participantes;
       this.rivals = rivals;
    }
   
    public Integer getIdEnfrentamiento() {
        return this.idEnfrentamiento;
    }
    
    public void setIdEnfrentamiento(Integer idEnfrentamiento) {
        this.idEnfrentamiento = idEnfrentamiento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTop() {
        return this.top;
    }
    
    public void setTop(String top) {
        this.top = top;
    }
    public int getParticipantes() {
        return this.participantes;
    }
    
    public void setParticipantes(int participantes) {
        this.participantes = participantes;
    }
    public Set getRivals() {
        return this.rivals;
    }
    
    public void setRivals(Set rivals) {
        this.rivals = rivals;
    }




}


