package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

import java.util.HashSet;
import java.util.Set;

/**
 * Enfrentamiento generated by hbm2java
 */
@Setter
@Getter
public class Enfrentamiento  implements java.io.Serializable {


     private Integer idEnfrentamiento;
     private String nombre;
     private String top;
     private int participantes;
     private Set<Rival> rivals = new HashSet(0);

    public Enfrentamiento() {
    }

    public Enfrentamiento(String nombre, String top, int participantes, Set rivals) {
       this.nombre = nombre;
       this.top = top;
       this.participantes = participantes;
       this.rivals = rivals;
    }

}


