package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Juego generated by hbm2java
 */
public class Juego  implements java.io.Serializable {


     private int idArticulo;
     private Consola consola;
     private Articulo articulo;
     private Date anioLanzamiento;
     private int jugadoresPvp;
     private Set torneos = new HashSet(0);

    public Juego() {
    }

    public Juego(Consola consola, Articulo articulo, Date anioLanzamiento, int jugadoresPvp, Set torneos) {
       this.consola = consola;
       this.articulo = articulo;
       this.anioLanzamiento = anioLanzamiento;
       this.jugadoresPvp = jugadoresPvp;
       this.torneos = torneos;
    }
   
    public int getIdArticulo() {
        return this.idArticulo;
    }
    
    public void setIdArticulo(int idArticulo) {
        this.idArticulo = idArticulo;
    }
    public Consola getConsola() {
        return this.consola;
    }
    
    public void setConsola(Consola consola) {
        this.consola = consola;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public Date getAnioLanzamiento() {
        return this.anioLanzamiento;
    }
    
    public void setAnioLanzamiento(Date anioLanzamiento) {
        this.anioLanzamiento = anioLanzamiento;
    }
    public int getJugadoresPvp() {
        return this.jugadoresPvp;
    }
    
    public void setJugadoresPvp(int jugadoresPvp) {
        this.jugadoresPvp = jugadoresPvp;
    }
    public Set getTorneos() {
        return this.torneos;
    }
    
    public void setTorneos(Set torneos) {
        this.torneos = torneos;
    }




}


