package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Juego generated by hbm2java
 */
@Setter
@Getter
public class Juego  implements java.io.Serializable {


     private int idArticulo;
     private Consola consola;
     private Articulo articulo;
     private Date anioLanzamiento;
     private int jugadoresPvp;
     private Set torneos = new HashSet(0);

    public Juego() {
    }

    public Juego(Consola consola, Articulo articulo, Date anioLanzamiento, int jugadoresPvp, Set torneos) {
       this.consola = consola;
       this.articulo = articulo;
       this.anioLanzamiento = anioLanzamiento;
       this.jugadoresPvp = jugadoresPvp;
       this.torneos = torneos;
    }

}


