package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Juego generated by hbm2java
 */
@Setter
@Getter
public class Juego extends Articulo implements java.io.Serializable {

     private Consola consola;
     private int anioLanzamiento;
     private int jugadoresPvp;
     private Set torneos = new HashSet(0);

    public Juego() {
    }

    public Juego(Integer idArticulo, String nombre) {
        this.setIdArticulo(idArticulo);
        this.setNombre(nombre);
    }

    public Juego(Integer idArticulo, Consola consola, int anioLanzamiento, int jugadoresPvp) {
        this.setIdArticulo(idArticulo);
        this.consola = consola;
        this.anioLanzamiento = anioLanzamiento;
        this.jugadoresPvp = jugadoresPvp;
    }


    public Juego(Integer idArticulo, Consola consola, int anioLanzamiento, int jugadoresPvp, String nombre) {
        this.setIdArticulo(idArticulo);
        this.consola = consola;
        this.anioLanzamiento = anioLanzamiento;
        this.jugadoresPvp = jugadoresPvp;
        this.setNombre(nombre);
    }

}


