package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final



/**
 * ParticipacionId generated by hbm2java
 */
public class ParticipacionId  implements java.io.Serializable {


     private int idTorneo;
     private int idUsuario;

    public ParticipacionId() {
    }

    public ParticipacionId(int idTorneo, int idUsuario) {
       this.idTorneo = idTorneo;
       this.idUsuario = idUsuario;
    }
   
    public int getIdTorneo() {
        return this.idTorneo;
    }
    
    public void setIdTorneo(int idTorneo) {
        this.idTorneo = idTorneo;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ParticipacionId) ) return false;
		 ParticipacionId castOther = ( ParticipacionId ) other; 
         
		 return (this.getIdTorneo()==castOther.getIdTorneo())
 && (this.getIdUsuario()==castOther.getIdUsuario());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdTorneo();
         result = 37 * result + this.getIdUsuario();
         return result;
   }   


}


