package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Participacion generated by hbm2java
 */
@Setter
@Getter
public class Participacion  implements java.io.Serializable {


     private ParticipacionId id;
     private Torneo torneo;
     private Usuario usuario;
     private Timestamp fechaRegistro;
     private Set<Rival> rivals = new HashSet(0);

    public Participacion() {
    }

    public Participacion(ParticipacionId id, Usuario usuario) {
        this.id = id;
        this.usuario = usuario;
    }

    public Participacion(ParticipacionId id, Torneo torneo, Usuario usuario, Timestamp fechaRegistro, Set rivals) {
       this.id = id;
       this.torneo = torneo;
       this.usuario = usuario;
       this.fechaRegistro = fechaRegistro;
       this.rivals = rivals;
    }

}


