package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Participacion generated by hbm2java
 */
public class Participacion  implements java.io.Serializable {


     private ParticipacionId id;
     private Torneo torneo;
     private Usuario usuario;
     private Timestamp fechaRegistro;
     private Set rivals = new HashSet(0);

    public Participacion() {
    }

    public Participacion(ParticipacionId id, Torneo torneo, Usuario usuario, Timestamp fechaRegistro, Set rivals) {
       this.id = id;
       this.torneo = torneo;
       this.usuario = usuario;
       this.fechaRegistro = fechaRegistro;
       this.rivals = rivals;
    }
   
    public ParticipacionId getId() {
        return this.id;
    }
    
    public void setId(ParticipacionId id) {
        this.id = id;
    }
    public Torneo getTorneo() {
        return this.torneo;
    }
    
    public void setTorneo(Torneo torneo) {
        this.torneo = torneo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Timestamp getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Timestamp fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set getRivals() {
        return this.rivals;
    }
    
    public void setRivals(Set rivals) {
        this.rivals = rivals;
    }




}


