package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
@Setter
@Getter
public class Pedido  implements java.io.Serializable {


     private Integer idPedido;
     private Usuario usuario;
     private Date fecha;
     private BigDecimal importe;
     private Set articuloPedidos = new HashSet(0);

    public Pedido() {
    }

    public Pedido(Usuario usuario, Date fecha, BigDecimal importe, Set articuloPedidos) {
       this.usuario = usuario;
       this.fecha = fecha;
       this.importe = importe;
       this.articuloPedidos = articuloPedidos;
    }

}


