package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import java.math.BigDecimal;
import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Integer idPedido;
     private Usuario usuario;
     private Date fecha;
     private BigDecimal importe;
     private Set articuloPedidos = new HashSet(0);

    public Pedido() {
    }

    public Pedido(Usuario usuario, Date fecha, BigDecimal importe, Set articuloPedidos) {
       this.usuario = usuario;
       this.fecha = fecha;
       this.importe = importe;
       this.articuloPedidos = articuloPedidos;
    }
   
    public Integer getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(Integer idPedido) {
        this.idPedido = idPedido;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getImporte() {
        return this.importe;
    }
    
    public void setImporte(BigDecimal importe) {
        this.importe = importe;
    }
    public Set getArticuloPedidos() {
        return this.articuloPedidos;
    }
    
    public void setArticuloPedidos(Set articuloPedidos) {
        this.articuloPedidos = articuloPedidos;
    }




}


