package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

/**
 * RivalId generated by hbm2java
 */
@Setter
@Getter
public class RivalId  implements java.io.Serializable {


     private int idEnfrentamiento;
     private int idTorneo;
     private int idUsuario;

    public RivalId() {
    }

    public RivalId(int idEnfrentamiento, int idTorneo, int idUsuario) {
       this.idEnfrentamiento = idEnfrentamiento;
       this.idTorneo = idTorneo;
       this.idUsuario = idUsuario;
    }

    public int getIdEnfrentamiento() {
        return this.idEnfrentamiento;
    }

    public void setIdEnfrentamiento(int idEnfrentamiento) {
        this.idEnfrentamiento = idEnfrentamiento;
    }
    public int getIdTorneo() {
        return this.idTorneo;
    }

    public void setIdTorneo(int idTorneo) {
        this.idTorneo = idTorneo;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RivalId) ) return false;
		 RivalId castOther = ( RivalId ) other; 
         
		 return (this.getIdEnfrentamiento()==castOther.getIdEnfrentamiento())
 && (this.getIdTorneo()==castOther.getIdTorneo())
 && (this.getIdUsuario()==castOther.getIdUsuario());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdEnfrentamiento();
         result = 37 * result + this.getIdTorneo();
         result = 37 * result + this.getIdUsuario();
         return result;
   }   


}


