package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final



/**
 * Rival generated by hbm2java
 */
public class Rival  implements java.io.Serializable {


     private RivalId id;
     private Participacion participacion;
     private Enfrentamiento enfrentamiento;
     private Boolean esGanador;

    public Rival() {
    }

    public Rival(RivalId id, Participacion participacion, Enfrentamiento enfrentamiento, Boolean esGanador) {
       this.id = id;
       this.participacion = participacion;
       this.enfrentamiento = enfrentamiento;
       this.esGanador = esGanador;
    }
   
    public RivalId getId() {
        return this.id;
    }
    
    public void setId(RivalId id) {
        this.id = id;
    }
    public Participacion getParticipacion() {
        return this.participacion;
    }
    
    public void setParticipacion(Participacion participacion) {
        this.participacion = participacion;
    }
    public Enfrentamiento getEnfrentamiento() {
        return this.enfrentamiento;
    }
    
    public void setEnfrentamiento(Enfrentamiento enfrentamiento) {
        this.enfrentamiento = enfrentamiento;
    }
    public Boolean getEsGanador() {
        return this.esGanador;
    }
    
    public void setEsGanador(Boolean esGanador) {
        this.esGanador = esGanador;
    }




}


