package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

/**
 * Rival generated by hbm2java
 */
@Setter
@Getter
public class Rival  implements java.io.Serializable {


     private RivalId id;
     private Participacion participacion;
     private Enfrentamiento enfrentamiento;
     private Boolean esGanador;

    public Rival() {
    }

    public Rival(RivalId id, Participacion participacion, Enfrentamiento enfrentamiento, Boolean esGanador) {
       this.id = id;
       this.participacion = participacion;
       this.enfrentamiento = enfrentamiento;
       this.esGanador = esGanador;
    }

}


