package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Sala generated by hbm2java
 */
public class Sala  implements java.io.Serializable {


     private Integer idSala;
     private String nombre;
     private int tamanio;
     private Set torneos = new HashSet(0);

    public Sala() {
    }

    public Sala(String nombre, int tamanio, Set torneos) {
       this.nombre = nombre;
       this.tamanio = tamanio;
       this.torneos = torneos;
    }
   
    public Integer getIdSala() {
        return this.idSala;
    }
    
    public void setIdSala(Integer idSala) {
        this.idSala = idSala;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getTamanio() {
        return this.tamanio;
    }
    
    public void setTamanio(int tamanio) {
        this.tamanio = tamanio;
    }
    public Set getTorneos() {
        return this.torneos;
    }
    
    public void setTorneos(Set torneos) {
        this.torneos = torneos;
    }




}


