package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

import java.util.HashSet;
import java.util.Set;

/**
 * Sala generated by hbm2java
 */
@Setter
@Getter
public class Sala  implements java.io.Serializable {


     private Integer idSala;
     private String nombre;
     private int tamanio;
     private Set torneos = new HashSet(0);

    public Sala() {
    }

    public Sala(String nombre, int tamanio, Set torneos) {
       this.nombre = nombre;
       this.tamanio = tamanio;
       this.torneos = torneos;
    }

}


