package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

/**
 * Stock generated by hbm2java
 */
@Setter
@Getter
public class Stock  implements java.io.Serializable {


     private Integer idStock;
     private Integer idArticulo;
     private int cantidad;

    public Stock() {
    }

    public Stock(Integer idStock, int cantidad) {
       this.idStock = idStock;
       this.cantidad = cantidad;
    }

}


