package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

import java.util.HashSet;
import java.util.Set;

/**
 * TipoUsuario generated by hbm2java
 */

@Getter
@Setter
public class TipoUsuario  implements java.io.Serializable {


     private Integer idTipoUsuario;
     private TipoUsuario tipo;
     private Set usuarios = new HashSet(0);

    public TipoUsuario() {
    }

    public TipoUsuario(TipoUsuario tipo, Set usuarios) {
       this.tipo = tipo;
       this.usuarios = usuarios;
    }


}


