package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Torneo generated by hbm2java
 */
public class Torneo  implements java.io.Serializable {


     private Integer idTorneo;
     private Juego juego;
     private Sala sala;
     private Usuario usuario;
     private Date fecha;
     private Set participacions = new HashSet(0);

    public Torneo() {
    }

    public Torneo(Juego juego, Sala sala, Usuario usuario, Date fecha, Set participacions) {
       this.juego = juego;
       this.sala = sala;
       this.usuario = usuario;
       this.fecha = fecha;
       this.participacions = participacions;
    }
   
    public Integer getIdTorneo() {
        return this.idTorneo;
    }
    
    public void setIdTorneo(Integer idTorneo) {
        this.idTorneo = idTorneo;
    }
    public Juego getJuego() {
        return this.juego;
    }
    
    public void setJuego(Juego juego) {
        this.juego = juego;
    }
    public Sala getSala() {
        return this.sala;
    }
    
    public void setSala(Sala sala) {
        this.sala = sala;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getParticipacions() {
        return this.participacions;
    }
    
    public void setParticipacions(Set participacions) {
        this.participacions = participacions;
    }




}


