package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;
import org.example.retropvpadmin.model.enums.TorneoEstadoEnum;

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Torneo generated by hbm2java
 */

@Getter
@Setter
public class Torneo  implements java.io.Serializable {


     private Integer idTorneo;
     private Juego juego;
     private Sala sala;
     private Usuario usuario;
     private Date fecha;
     private Set participacions = new HashSet(0);
     private TorneoEstadoEnum torneoEstadoEnum;

    public Torneo() {
    }

    public Torneo(Juego juego, Sala sala, Usuario usuario, Date fecha, Set participacions, TorneoEstadoEnum torneoEstadoEnum) {
       this.juego = juego;
       this.sala = sala;
       this.usuario = usuario;
       this.fecha = fecha;
       this.participacions = participacions;
       this.torneoEstadoEnum = torneoEstadoEnum;
    }

}


