package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private TipoUsuario tipoUsuario;
     private String nombre;
     private String apellido;
     private String email;
     private String direccion;
     private String telefono;
     private Set participacions = new HashSet(0);
     private Set pedidos = new HashSet(0);
     private Set torneos = new HashSet(0);

    public Usuario() {
    }

    public Usuario(TipoUsuario tipoUsuario, String nombre, String apellido, String email, String direccion, String telefono, Set participacions, Set pedidos, Set torneos) {
       this.tipoUsuario = tipoUsuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.email = email;
       this.direccion = direccion;
       this.telefono = telefono;
       this.participacions = participacions;
       this.pedidos = pedidos;
       this.torneos = torneos;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public TipoUsuario getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getParticipacions() {
        return this.participacions;
    }
    
    public void setParticipacions(Set participacions) {
        this.participacions = participacions;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }
    public Set getTorneos() {
        return this.torneos;
    }
    
    public void setTorneos(Set torneos) {
        this.torneos = torneos;
    }




}


