package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
@Getter
@Setter
@AllArgsConstructor
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private TipoUsuario tipoUsuario;
     private String nombre;
     private String apellido;
     private String email;
     private String direccion;
     private String telefono;
     private Set participacions = new HashSet(0);
     private Set pedidos = new HashSet(0);
     private Set torneos = new HashSet(0);

    public Usuario() {
    }

    public Usuario(TipoUsuario tipoUsuario, String nombre, String apellido, String email, String direccion, String telefono, Set participacions, Set pedidos, Set torneos) {
       this.tipoUsuario = tipoUsuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.email = email;
       this.direccion = direccion;
       this.telefono = telefono;
       this.participacions = participacions;
       this.pedidos = pedidos;
       this.torneos = torneos;
    }

}


