package org.example.retropvpadmin.model;
// Generated 22 abr 2026, 12:54:41 by Hibernate Tools 6.2.8.Final


import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.example.retropvpadmin.config.SchemDB;

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
@NoArgsConstructor
@Getter
@Setter
public class Usuario implements java.io.Serializable {


    private long idUsuario;
    private long tipoUsuario;
    private String nombre;
    private String apellido;
    private String email;
    private String direccion;
    private String telefono;
    private String DNI;
    private Set participacions = new HashSet(0);
    private Set pedidos = new HashSet(0);
    private Set torneos = new HashSet(0);

    public Usuario(long idUsuario, long tipoUsuario, String nombre, String apellido, String email, String direccion, String telefono, String DNI) {
        this.idUsuario = idUsuario;
        this.tipoUsuario = tipoUsuario;
        this.nombre = nombre;
        this.apellido = apellido;
        this.email = email;
        this.direccion = direccion;
        this.telefono = telefono;
        this.DNI = DNI;
    }

    public Usuario(long tipoUsuario, String nombre, String apellido, String email, String direccion, String telefono, Set participacions, Set pedidos, Set torneos) {
        this.tipoUsuario = tipoUsuario;
        this.nombre = nombre;
        this.apellido = apellido;
        this.email = email;
        this.direccion = direccion;
        this.telefono = telefono;
        this.participacions = participacions;
        this.pedidos = pedidos;
        this.torneos = torneos;
    }

    public Usuario(long idUsuario, String nombre, String apellido) {
        this.idUsuario = idUsuario;
        this.nombre = nombre;
        this.apellido = apellido;
    }

}


